Carrito/urls.py
from django.conf.urls import url
from .views import cart, Cart_Items, Cart_delete
app_name = 'Cart'
urlpatterns = [
    url(r'^(?P<username>[A-Za-z0-9_.-]+)/$', Cart_Items, name='Cart'),
    url(r'^(?P<username>[A-Za-z0-9_.-]+)/add/$', cart, name = 'add_to_cart'),
    url(r'^(?P<username>[A-Za-z0-9_.-]+)/(?P<pk>[0-9]+)/delete/$', Cart_delete, name = 'Cart_delete'),
]

GO_KART/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import homepage

from Accounts.views import login_view, logout_view, register_view, auth_view
from Seller.views import AddProduct, results
from Orders.views import orders, Display_Orders, Delete_Order
from django.conf import settings
from django.conf.urls.static import static
from Cart.views import Cart_Items, Cart_delete, cart
from Redirect.views import redirect
app_name = 'GO_KART'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', homepage, name = 'homepage'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^auth/$', auth_view, name='authenticate'),
    url(r'^register/$', register_view, name='register'),
    url(r'^sell-item/$', AddProduct.as_view(), name = 'AddProduct'),
    url(r'^selling-items/', include('Seller.urls')),
    url(r'^results/$', results, name = 'query_result'),
    url(r'^cart/', include('Cart.urls')),
    url(r'redirect/(?P<Seller>[A-Za-z]+)/(?P<Product_Name>[A-Za-z0-9]+)/', include('Redirect.urls')),
    url(r'^orders/(?P<Username>[a-zA-Z0-9_.-]+)/(?P<pk>[0-9]+)/add/$', orders, name = 'Orders'),
    url(r'^orders/(?P<Username>[a-zA-Z0-9_.-]+)/$', Display_Orders, name = 'Display-Orders'),
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', Delete_Order, name = 'Delete-Order'),
    url(r'redirect/(?P<Seller>[a-zA-Z])/(?P<Product_Name>[a-zA-Z0-9]+)/$', redirect, name = 'redirect'),

]
if settings.DEBUG:              #True if in development mode
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Seller/urls.py
from django.conf.urls import url
from .views import selling_items, Delete_Selling_Item
app_name = 'Seller'
urlpatterns = [
    url(r'^$', selling_items, name = 'SellingItems'),
    url(r'^(?P<Seller>[a-zA-Z0-9_.-]+)/(?P<pk>[0-9]+)/delete/$', Delete_Selling_Item, name = 'Delete-Selling-Items'),
]

Seller/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
class ProductDescription(models.Model):
    Seller_Username = models.CharField(max_length = 100, null = False)
    Category = models.CharField(max_length = 100, null = False)
    Company_Name = models.CharField(max_length = 100, null = False)
    Product_Name = models.CharField(max_length = 100, null = False)
    Price = models.CharField(max_length = 10, null = False)
    Additional_Information = models.CharField(max_length=100, null=False)
    Product_Image = models.FileField(max_length=1000, null=True)
    def get_absolute_url(self):
        return reverse('Seller:SellingItems')
    def __str__(self):
        return self.Product_Name + ' - ' + self.Seller_Username

# Create your models here.

Seller/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from .models import ProductDescription
from django.shortcuts import render_to_response
flag = False
class AddProduct(CreateView):
    model = ProductDescription
    fields = ['Category', 'Product_Name', 'Company_Name', 'Price', 'Product_Image', ]
    def form_valid(self, form):
        user = self.request.user
        form.instance.Seller_Username = user
        return super(AddProduct, self).form_valid(form)
def selling_items(request):
    Seller = request.user
    object = ProductDescription.objects.filter(Seller_Username=Seller)
    return render(request, 'Seller/SellingItems.html', {'items': object,})
def results(request):
    query = request.GET.get('q').strip()
    if (query == ''):
        return redirect('/')
    if(query.lower() == 'all'):
        data = ProductDescription.objects.all().order_by('Price')
        return render(request, 'Seller/SearchBar.html', {'object': data, 'query': query})
    for check in ProductDescription.objects.all():
        if(check.Product_Name.lower() == query.lower()):
            data = ProductDescription.objects.filter(Product_Name = query).order_by('Price')
            return render(request, 'Seller/SearchBar.html', {'object': data, 'query': query})
        elif(check.Category.lower() == query.lower()):
            data = ProductDescription.objects.filter(Category=query).order_by('Price')
            return render(request, 'Seller/SearchBar.html', {'object': data, 'query': query})
        elif(check.Company_Name.lower() == query.lower()):
            data = ProductDescription.objects.filter(Company_Name=query).order_by('Price')
            return render(request, 'Seller/SearchBar.html', {'object': data, 'query': query})
        elif(check.Seller_Username.lower() == query.lower()):
                data = ProductDescription.objects.filter(Seller_Username=query).order_by('Price')
                return render(request, 'Seller/SearchBar.html', {'object': data, 'query': query})
    return render(request, 'Seller/NoItem.html', {'object': query})
def Delete_Selling_Item(request, pk, Seller):
    object = ProductDescription.objects.get(pk = pk)
    object.delete()
    object = ProductDescription.objects.filter(Seller_Username = Seller)
    return render(request, 'Seller/SellingItems.html', {'items': object, 'Seller': Seller})

# Create your views here.

Seller/templates/Seller/NoItem.html
{% extends 'GO_KART/base.html' %}
{% block title %}Item no encontrado!{% endblock %}
{%block body%}
{{data}}
<h4 class = "alert alert-danger">Lo sentimos, no se encontraron resultados!
Revisa la escritura para {{ object }} o intenta otra nueva busqueda</h4>
{% endblock %}

Seller/templates/Seller/SearchBar.html
<title>Items para vender</title>
{% extends 'GO_KART/base.html' %}
{% block body %}
{% load staticfiles%}
<div class = 'container'>
    <h2>Resultados para {{ query }}</h2>
</div>
    <script>
function Split(Seller_Username, UniqueKey, Username){
    var Username = Username;
    var str = Seller_Username;
    var str1 = document.getElementById(UniqueKey).innerHTML;
    if(str ==    "Flipkart"){
    str1 = str1.replace(" ", "%20");
    window.open('https://Flipkart.com/search?q=' + str1);}
    else if (str == "Amazon"){
        str1 = str1.replace(" ", "%20");
        window.open('https://www.amazon.in/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=' + str1);}
    else if (str == "Myntra"){
        str1 = str1.replace(" ", "%20");
        window.open('https://www.myntra.com/' + str1 + '?userQuery=true');}
    else{
    window.location = '/orders/' + Username + '/' + UniqueKey + '/add/';
    }
}
</script>

        {% for field in object %}
        {% csrf_token %}
            <div class = 'container'>
            <div class = "panel panel-default col-md-12">
                <div class = "panel panel-default col-md-4">
                    <div class = "album">
                        <a href = ""><img  src = '{{field.Product_Image.url}}' class = "img-responsive" width="400" height="236"></a>
                    </div>
                </div>
                <h3><b><span id={{field.pk}}>{{field.Product_Name}}</span></b><br>&nbsp;Precio: <b>COP{{ field.Price }}</b></h3>
                <h3>&nbsp;Fabricante: <b>{{ field.Company_Name }}</b></h3>
                <h3>&nbsp;Vendedor: <b>{{ field.Seller_Username }}</b> </h3>
                <form action = "{% url 'Cart:add_to_cart'  user.username  %}" method="POST" style="display:inline">
                    {% csrf_token %}
                    <button type="submit" class = "btn btn-primary" name = 'Add_to_Cart' value = '{{ field.pk }}' ><span class = "glyphicon glyphicon-plus"></span>&nbsp;Añadir al Carrito</button>
                </form>
                    <button type="submit" onclick = Split('{{field.Seller_Username}}','{{field.pk}}','{{user.username}}') class = "btn btn-success" name = 'Buy' value = '{{ field.pk }}'>&nbsp;Comprar</button>
            </div>

            </div>

        {% endfor %}
{% endblock %}

Seller/templates/Seller/SellingItems.html
<title>Items para vender</title>
{% extends 'GO_KART/base.html' %}
{% block body %}
        {% load staticfiles%}

{% if items %}
        <div class = 'container'>
            <h2>Tus items a la venta</h2>
            <br>
        </div>
                <div class = 'container'>
        {% for item in items %}
            <!--{% if item.Seller_Username == user.username %}-->
                {% csrf_token %}

                    <div class = "panel panel-default col-md-4">
                        <div class = "album">
                            <a href = ""><img  src = '{{item.Product_Image.url}}' class = "img-responsive" width="400" height="236"></a>
                        </div>
                        <h4><b>{{item.Product_Name}} </b>  |   Precio de Venta: <b>COP{{ item.Price }}</b>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<form action = "/selling-items/{{user.username}}/{{item.pk}}/delete/" method="POST" style="display:inline">
                                    <input type="hidden" name='' value=""/>
                                    {% csrf_token %}
                                    <button type="submit" class = "btn btn-default"><span class = "glyphicon glyphicon-trash"></span></button>
                        </form></h4>
                    </div>

            <!--{% endif %}-->
        {% endfor %}
                    </div>

{% else %}
    <div class = 'container'>
        <h2 class = "alert alert-danger">Aun no tienes items a la venta.</h2>
        <br>
    </div>
{% endif %}
{% endblock %}

Seller/templates/Seller/form-template.html
<title>Vender en Go Kart</title>
{{form.Seller_Username}}
{% for field in form %}
<div class = "form-group">
    <div class = "col-sm-offset-2"><span class = "text-danger small ">{{field.errors}}</span></div>
    <label class = "control-label col-sm-2">{{ field.label_tag }}</label>
    <div class = "col-sm-10">{{ field }}</div>
</div>
{% endfor %}

Seller/templates/Seller/productdescription_form.html
{% extends 'GO_KART/base.html' %}
<title>Sell</title>
{% block body%}
<div class = "container">
    <div class = "row">
        <div class = "col-sm-12 col-md-6">
            <div class = "panel panel-default">
                <br>
                <form class = "form-horizontal" action = "" method = "post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'Seller/form-template.html' %}
                    <div class = "form-group">
                        <div class = "col-md-offset-2 col-md-2">
                            <a href=""><button type = "submit" class="btn btn-success">Agregar</button></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}