Cuentas/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'Accounts'
urlpatterns = [url(r'^$', views.login_view, name ='login'),
               url(r'^loggedin/$', views.auth_view, name = 'authenticate'),
               url(r'^logout$', views.logout_view, name='logout'),
                   ]

GO_KART/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import homepage

from Accounts.views import login_view, logout_view, register_view, auth_view
from Seller.views import AddProduct, results
from Orders.views import orders, Display_Orders, Delete_Order
from django.conf import settings
from django.conf.urls.static import static
from Cart.views import Cart_Items, Cart_delete, cart
from Redirect.views import redirect
app_name = 'GO_KART'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', homepage, name = 'homepage'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^auth/$', auth_view, name='authenticate'),
    url(r'^register/$', register_view, name='register'),
    url(r'^sell-item/$', AddProduct.as_view(), name = 'AddProduct'),
    url(r'^selling-items/', include('Seller.urls')),
    url(r'^results/$', results, name = 'query_result'),
    url(r'^cart/', include('Cart.urls')),
    url(r'redirect/(?P<Seller>[A-Za-z]+)/(?P<Product_Name>[A-Za-z0-9]+)/', include('Redirect.urls')),
    url(r'^orders/(?P<Username>[a-zA-Z0-9_.-]+)/(?P<pk>[0-9]+)/add/$', orders, name = 'Orders'),
    url(r'^orders/(?P<Username>[a-zA-Z0-9_.-]+)/$', Display_Orders, name = 'Display-Orders'),
    url(r'^orders/(?P<pk>[0-9]+)/delete/$', Delete_Order, name = 'Delete-Order'),
    url(r'redirect/(?P<Seller>[a-zA-Z])/(?P<Product_Name>[a-zA-Z0-9]+)/$', redirect, name = 'redirect'),

]
if settings.DEBUG:              #True if in development mode
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Seller/urls.py
from django.conf.urls import url
from .views import selling_items, Delete_Selling_Item
app_name = 'Seller'
urlpatterns = [
    url(r'^$', selling_items, name = 'SellingItems'),
    url(r'^(?P<Seller>[a-zA-Z0-9_.-]+)/(?P<pk>[0-9]+)/delete/$', Delete_Selling_Item, name = 'Delete-Selling-Items'),
]

Cuentas/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Cuentas/forms.py
from django import forms
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.models import User
from django.shortcuts import redirect
User = get_user_model()
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password = password)
        if username and password:
            if not user:               # to check if the password is correct
                raise forms.ValidationError("Invalid Credentials")
            if not user.is_active:
                raise forms.ValidationError("User is not Active")
            return super(UserLoginForm, self).clean(*args, **kwargs)
        return redirect('/invalid')
class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label = 'Email')
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(label = 'Confirm Password', widget = forms.PasswordInput)
    mobile_number = forms.CharField(min_length=10, max_length=10)
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password', 'password_confirm', 'mobile_number']
    def clean(self, *args, **kwargs):
        check1 = self.cleaned_data.get('password')
        check2 = self.cleaned_data.get('password_confirm')
        if (check1 != check2):
            raise forms.ValidationError('Password must match!')
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        mobile_number = self.cleaned_data.get('mobile_number')
        emailqs = User.objects.filter(email = email)
        usernameqs = User.objects.filter(username = username)
        mobile_numberqs = User.objects.filter(username=mobile_number)
        if (emailqs.exists()):
            raise forms.ValidationError('Email ID already exists')
        if(usernameqs.exists()):
            raise forms.ValidationError('Username already exists')
        if(mobile_numberqs.exists()):
            raise forms.ValidationError('Mobile number already exists')
        return super(RegisterForm, self).clean(*args, **kwargs)

Cuentas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import authenticate, login, logout, get_user_model
from Accounts.forms import UserLoginForm, RegisterForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django import forms
def login_view(request):
    form = UserLoginForm(request.POST or None)
    return  render(request, "Accounts/Login.html", {'form': form, 'title': 'Login'})
def auth_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password=password)
        if not user:
            raise forms.ValidationError('Invaid credentials.')
        else:
            if user.is_active:
                auth.login(request, user)
                return redirect('/')
def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit = False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username = user.username, password = password)
        login(request, new_user)
        return redirect('/')
    context = {'form': form, 'title': 'Register'}
    return  render(request, 'Accounts/form.html', context)
def logout_view(request):
    logout(request)
    return  redirect('/')

Cuentas/templates/Accounts/Invalid.html
{% extends 'GO_KART/base.html' %}
{% include 'Accounts/loginpartial.html'%}
{% block body %}

{% load staticfiles%}
<h1>Invalid Credentials Please Log in again!</h1>
{%%}

Cuentas/templates/Accounts/Login.html
{% load crispy_forms_tags %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<div class = "container">
    <h2> {{title}} </h2>
<form class = "form" action = "/auth/" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class = "col-md-2">
            <input type = "submit" class = "btn btn-default btn-block" value="Login" required></input>
        </div>
</form>
</div>

Cuentas/templates/Accounts/form.html
{% load crispy_forms_tags %}
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<div class = "container">
    <h2> {{title}} </h2>
<form class = "form" action = "" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class = "col-md-2">
            <input type = "submit" class = "btn btn-default btn-block" value="{{title}}"></input>
        </div>
</form>
</div>

Cuentas/templates/Accounts/loginpartial.html
{% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href = "/cart/{{user.username}}/ "><span class = "glyphicon glyphicon-shopping-cart"></span>&nbsp;Carro de Compras</a></li>
        <li><a href = "/sell-item"><span class = "glyphicon glyphicon-usd"></span>&nbsp; Vender</a></li>
        <li class = "dropdown">
                    <a href =#" class = "dropdown-toggle" data-toggle = "dropdown"><span class = "glyphicon glyphicon-user"></span>&nbsp; Hola {{ user.username }}<span class = "caret"></span></a>
                    <ul class = "dropdown-menu">
                        <li><a href="/orders/{{user.username}}/">Ordenes de Compra</a> </li>
                        <li><a href="{% url 'Seller:SellingItems'%}">Ventas</a></li>
                        <li><a href = '/logout'>Logout</a> </li>
                    </ul>
                </li>
    </ul>
    <form class = "navbar-form navbar-left" role = "search" method="get" action = "/results/">
                <div class = "form-group search">
                    <input type = "text" value = "" name = "q" placeholder = "Buscar productos" required>
                </div>
                <button type = "submit" class = "btn btn-primary"><span class = "glyphicon glyphicon-search"></span>&nbsp;</button>
    </form>
{% else %}
<ul class="nav navbar-nav navbar-right">
    <li><a href="/login"><span class = "glyphicon glyphicon-log-in"></span>&nbsp;Log in</a></li>
	<li><a href = "/register"><span class = "glyphicon glyphicon-user"></span>&nbsp; Registrarse</a></li>
</ul>

{% endif %}
                